// Shared resume data for the AI assistant serverless function
export const RESUME_DATA = {
  personalInfo: {
    name: "Rishitha Mondi",
    title: "AI/ML & Full-Stack Engineer",
    subTitle: "B.Tech in CSE (Data Science)",
    cgpa: "9.36",
    institution: "Vignan's Institute of Information Technology",
    location: "Visakhapatnam, Andhra Pradesh, India",
    email: "rishithashivanandh@gmail.com",
    phone: "+91 6304075658",
    socialLinks: {
      github: "https://github.com/rishithamondi",
      linkedin: "https://www.linkedin.com/in/rishitha-shivanandh/",
      leetcode: "https://leetcode.com/u/rishithamondi/",
      codechef: "https://www.codechef.com/users/rishithamondi",
    },
    bio: "AI/ML and Full-Stack Developer with a 9.36 CGPA in Computer Science & Data Science. Focused on enterprise-grade conversational AI, high-concurrency microservices, and modern web applications.",
    currentFocus: "Architecting multilingual real-time AI speech & text streaming microservices and interactive coding analysis platforms.",
  },
  experience: [
    {
      role: "AI/ML Intern",
      company: "Kreative TimeBox Pvt. Ltd.",
      location: "Remote",
      period: "July 2026 – Present",
      isCurrent: true,
      bulletPoints: [
        "Contributing to ConversaAI, an enterprise multilingual conversational AI platform integrating LLMs, STT, TTS, real-time translation, and streaming via scalable microservices.",
        "Developing cross-platform web and mobile applications using React, React Native, WebSockets, REST APIs, and platform-wide feature integration.",
      ],
      techTags: ["LLMs", "STT/TTS", "React", "React Native", "WebSockets", "Microservices", "REST APIs"],
    },
    {
      role: "Web Developer Intern",
      company: "CodSoft",
      location: "Remote",
      period: "June 2025 – July 2025",
      isCurrent: false,
      bulletPoints: [
        "Built responsive React-based interfaces for a cloud cafe management platform integrating backend APIs and modular UI components.",
      ],
      techTags: ["React.js", "RESTful APIs", "UI Components"],
    },
  ],
  projects: [
    {
      id: "lucy-ai",
      title: "LUCY AI",
      subtitle: "AI-Powered Technical Interview & Voice Workspace Platform",
      techStack: ["Next.js", "FastAPI", "PostgreSQL", "OpenRouter", "faster-whisper", "OpenAI TTS", "Tailwind CSS"],
      solution: "Engineered an immersive voice AI technical interview platform synchronizing live voice transcripts, flowchart visualizers, dynamic complexity graphs, and isolated code evaluation.",
      highlights: [
        "Interactive flowchart visualizer mapping user logic to step-by-step execution graphs.",
        "Secure code execution engine evaluating live test cases with real-time metrics.",
        "Bidirectional voice AI with STT/TTS and automated performance rubric generation.",
      ],
      liveUrl: "https://lucy-ai-dsa.vercel.app/",
      githubUrl: "https://github.com/rishithamondi/lucy-ai",
    },
    {
      id: "leavex",
      title: "LeaveX",
      subtitle: "Hostel Leave Management System & Pass Engine",
      techStack: ["Next.js", "FastAPI", "TypeScript", "SupaBase", "Tailwind CSS", "JWT"],
      solution: "Architected a secure centralized platform automating the end-to-end leave application lifecycle with role-based dashboards and cryptographic QR digital passes.",
      highlights: [
        "Cryptographically signed QR token engine for instant digital verification.",
        "Real-time aggregation engine for active leave balances and statistics.",
        "Role-based authorization for students, wardens, and admin staff.",
      ],
      liveUrl: "https://leavex-hms.vercel.app/",
      githubUrl: "https://github.com/rishithamondi/leavex",
    },
    {
      id: "photo-frames",
      title: "Sri Lakshmi Ganapathi Frames",
      subtitle: "Custom E-Commerce Platform & Admin AI Suite",
      techStack: ["React.js", "TypeScript", "Node.js", "Express.js", "Neon", "Tailwind CSS"],
      solution: "Designed a high-performance e-commerce engine with relational eager loading, zero-disk streaming, and Gemini AI SEO generation.",
      highlights: [
        "Eliminated N+1 database queries via relational eager-loading.",
        "Gemini AI automated SEO content generation.",
        "Dual-mode deletion: soft-deletes and permanent removal with CDN cleanup.",
      ],
      liveUrl: "https://srilakshmiganapathiphotoframes.vercel.app/",
      githubUrl: "https://github.com/rishithamondi/SLGPhotoFrames",
    },
  ],
  skills: {
    languages: ["Python", "Java", "SQL", "JavaScript", "TypeScript"],
    frontend: ["React.js", "Next.js", "Tailwind CSS", "React Native"],
    backend: ["FastAPI", "Node.js", "Express.js", "RESTful APIs", "JWT Auth", "WebSockets"],
    aiml: ["Large Language Models (LLMs)", "faster-whisper (STT)", "OpenAI TTS", "OpenRouter APIs", "Gemini AI APIs"],
    databases: ["MySQL", "PostgreSQL", "MongoDB", "Neon SQL", "SupaBase"],
    tools: ["Git & GitHub", "Docker", "VS Code", "Postman", "Vercel", "Render"],
  },
  certifications: [
    { title: "Introduction to Generative AI", issuer: "Google Skills Boost" },
    { title: "HTML, CSS & Java, Python Essentials 1 & 2", issuer: "Cisco Networking Academy" },
    { title: "Power BI for Beginners", issuer: "Simplilearn" },
    { title: "Data Science Mastery", issuer: "Udemy" },
  ],
  achievements: [
    { title: "Reliance Foundation Undergraduate Scholarship", description: "Awarded for exceptional academic excellence and research potential." },
    { title: "Top 5 Position – Cursors Hackathon (ANITS)", description: "Secured Top 5 among competing technical teams for rapid software engineering." },
    { title: "Innovation Hackathons (IdeaThon & SusHacks)", description: "Finalist in university-level innovation events for sustainable software & AI solutions." },
    { title: "All India ServiceNow AI Skills Summit", description: "Delegate with hands-on exposure to enterprise AI and workflow automation." },
  ],
};
